### ISSUE TITLE
FP16_Optimizer in conjunction with log_lamb_rs causes KeyError

### ISSUE THREAD

**Issue by mmarius** [cybertronai/transformer-xl#17]
Skipping the optimizer step (https://github.com/cybertronai/transformer-xl/blob/master/fp16_opt.py#L439 ) in the very first iteration causes an empty state dict. 
This results in a KeyError from https://github.com/cybertronai/transformer-xl/blob/master/train.py#L536 .

**Comment by yaroslavvb** [comment]
Can you give a more detailed stack trace? If state_dict is empty I would expect the log_lamb_rs to do nothing:

https://github.com/cybertronai/pytorch-lamb/blob/ff2245eaa458278b096e682a66c29a2d73f690d7/pytorch_lamb/lamb.py#L14-L18

**Comment by mmarius** [comment]
https://github.com/cybertronai/pytorch-lamb/blob/ff2245eaa458278b096e682a66c29a2d73f690d7/pytorch_lamb/lamb.py#L18
This line will throw the key error. Because state does not contain 'r', 'r1', and 'r2'. They are added by the step function.

**Comment by yaroslavvb** [comment]
should be fixed in master version of lamb
