### ISSUE TITLE
model vs. model_to_reset in evaluate_and_log

### ISSUE THREAD

**Issue by xjsbyd** [cybertronai/transformer-xl#18]
I have a question regarding the [evaluate_and_log](https://github.com/cybertronai/transformer-xl/blob/master/train.py#L391) function. Shouldn't **model_to_reset** be passed to the [evaluate](https://github.com/cybertronai/transformer-xl/blob/master/train.py#L411) function instead of **model**?

**Comment by yaroslavvb** [comment]
both model_to_reset and model refer to the same model, the "model_to_reset" has one less level of wrapping, but the only difference is syntactic sugar
