### ISSUE TITLE
How to determine max_tokens ?

### ISSUE THREAD

**Issue by agemagician** [cybertronai/transformer-xl#20]
Hello,

How did you determined the max_tokens value ?
Is it the total number of tokens exist on the dataset ? 

Thanks in advance.

**Comment by yaroslavvb** [comment]
Yes, this is an approximate number of tokens in the dataset. It's used by learning rate scheduler -- ie, after max_tokens tokens the CosineAnnealing lr scheduler will drop learning rate

**Comment by agemagician** [comment]
Thanks a lot for the explanation.
